POST http://localhost:3333/courses
Content-Type: application/json

{
    "title": "Cur"
}
###

GET http://localhost:3333/courses

###

GET http://localhost:3333/courses/40a4a435-0b2d-46ae-a4d99-3dc5f3b0165f



